<?php
    $title = 'Users';
    $this->headTitle($title);
?>
<div class="get-quote">
    <div class="row">
        <div class="col-sm-11 col-12">
            <h1 id="quote"><?= $this->escapeHtml($title) ?></h1>
        </div>
        <div class="col-sm-1 col-12">
            <a href="<?= $this->url('user', ['action' => 'add']) ?>">
                <button type="button" class="btn btn-outline-primary">Add</button>
            </a>
        </div>
    </div>
</div>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Sr. No</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Contact No</th>
            <th>Profile Photo</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $key => $user) : ?>
            <tr>
                <td><?= $key+1 ?></td>
                <td><?= $this->escapeHtml($user->firstname) ?></td>
                <td><?= $this->escapeHtml($user->lastname) ?></td>
                <td><?= $this->escapeHtml($user->email) ?></td>
                <td><?= $this->escapeHtml($user->contact) ?></td>
                <td>
                    <img src="<?php echo $this->basePath() . '/img' . '/' . $user->profilephoto; ?>" class="img-thumbnail" 
                        alt="blog photos" width="50px;" height="50px;">'
                </td>
                <td>
                    <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>">
                        <i class="fa fa-pencil-square" style="font-size:24px"></i>
                    </a>
                    <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->id]) ?>">
                        <i class="fa fa-trash" style="font-size:24px"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?= $this->paginationControl(
    $this->paginator,
    'sliding',
    'partial/paginator',
    ['route' => 'user']
) ?>